/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerBarang;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelBarang;
import util.Koneksi;

/**
 *
 * @author Windows 10
 */
public class ViewBarang extends javax.swing.JFrame {
    Koneksi koneksi = new Koneksi();
    ControllerBarang cb = new ControllerBarang();
    ModelBarang mb = new ModelBarang();
    /**
     * Creates new form ViewBarang
     */
    public ViewBarang() {
        initComponents();
        setLocationRelativeTo(null);
        dataTable();
    }
     private void baru (){
        btn_baru.setText("Batal");
        btn_simpan.setEnabled(true);
        btn_bersih.setEnabled(true);
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
        btn_tutup.setEnabled(false);
        JT_namabarang.setEditable(true);
        jt_jenisbarang.setEditable(true);
        jt_jumlahbarang.setEditable(true);
        JT_idbarang.setText("");
        jt_jenisbarang.setText("");
        jt_jumlahbarang.setText("");
        JT_namabarang.setText("");
        bersih();
    }
    
    private void bersih2(){
        btn_baru.setEnabled(true);
        btn_simpan.setEnabled(false);
        btn_bersih.setEnabled(false);
        btn_ubah.setEnabled(false);
        btn_hapus.setEnabled(false);
        btn_tutup.setEnabled(false);
        JT_namabarang.setEditable(false);
        jt_jenisbarang.setEditable(false);
        jt_jumlahbarang.setEditable(false);
        bersih();
    }
    
    private void bersih(){
        JT_idbarang.setText("");
        JT_namabarang.setText("");
        jt_jenisbarang.setText("");
        jt_jumlahbarang.setText("");
        JT_namabarang.requestFocus();
        btn_baru.setText("baru");
        btn_simpan.setEnabled(false);
        btn_bersih.setEnabled(false);
        dataTable();
    }
    
    private void ubahDanHapus(){
      
        JT_namabarang.setEditable(true);
        jt_jenisbarang.setEditable(true);
        jt_jumlahbarang.setEditable(true);
        btn_hapus.setEnabled(true);
        btn_ubah.setEnabled(true);
        btn_bersih.setEnabled(true);
    }
    
    private void dataTable(){
        koneksi.koneksiDatabase();
        
        DefaultTableModel tabel = new DefaultTableModel();
        
        tabel.addColumn("id Barang");
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Jenis Barang");
        tabel.addColumn("Jumlah Barang");
        
        jTable2.setModel(tabel);
        try {
            String sql = "Select * from tbl_barang";
            
            ResultSet res = koneksi.state.executeQuery(sql);
            while (res.next()){
                tabel.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("jenis"),
                    res.getInt("jumlah")
                });
                jTable2.setModel(tabel);
            }
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, "Inputkan Data..!!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JT_idbarang = new javax.swing.JTextField();
        JT_namabarang = new javax.swing.JTextField();
        jt_jenisbarang = new javax.swing.JTextField();
        jt_jumlahbarang = new javax.swing.JTextField();
        btn_baru = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_tutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setEnabled(false);

        jLabel1.setText("id Barang            :");

        jLabel2.setText("Nama Barang      :");

        jLabel3.setText("Jenis Barang       :");

        jLabel4.setText("Jumlah Barang    :");

        JT_idbarang.setEnabled(false);

        btn_baru.setText("Baru");
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.setEnabled(false);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_bersih.setText("Bersih");
        btn_bersih.setEnabled(false);
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.setEnabled(false);
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.setEnabled(false);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_tutup.setText("Tutup");
        btn_tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tutupActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id Barang", "Nama Barang", "Jenis Barang", "Jumlah Barang"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(JT_idbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218)
                        .addComponent(btn_baru, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(JT_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btn_simpan)
                        .addGap(28, 28, 28)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(jt_jenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(btn_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_tutup, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(jt_jumlahbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(JT_idbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_baru)
                    .addComponent(btn_ubah))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(JT_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_simpan)
                    .addComponent(btn_hapus))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jt_jenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_bersih)
                    .addComponent(btn_tutup))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(jt_jumlahbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        // TODO add your handling code here:
         String logic = btn_baru.getText();
         if (logic.equals("Baru")) {
            baru();
        } else {
            bersih();
        }
    }//GEN-LAST:event_btn_baruActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String nama = JT_namabarang.getText();
            String jenis = jt_jenisbarang.getText();
            int jumlah = Integer.parseInt(jt_jumlahbarang.getText().trim());
           mb.setNama(nama);
            mb.setJenis(jenis);
            mb.setJumlah(jumlah);
            cb.simpanData(mb);
            dataTable();
            bersih2();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harap Masukan Barang");
            jt_jenisbarang.setText("");
            jt_jumlahbarang.setText("");
            jt_jenisbarang.requestFocus();
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        // TODO add your handling code here:
           bersih();
    }//GEN-LAST:event_btn_bersihActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(JT_idbarang.getText());
            String nama = JT_namabarang.getText();
            String jenis = jt_jenisbarang.getText();
            int jumlah = Integer.parseInt(jt_jumlahbarang.getText());

            mb.setId(id);
            mb.setNama(nama);
            mb.setJenis(jenis);
            mb.setJumlah(jumlah);

            bersih2();
            dataTable();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Harap Masukan Nama Barang");
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(JT_idbarang.getText());

            mb.setId(id);
            cb.hapusData(mb);

            dataTable();
            bersih2();
            bersih();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Harap Masukan Nama Barang");
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tutupActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_tutupActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        ubahDanHapus();
        try {
            int baris = jTable2.getSelectedRow();
            JT_idbarang.setText(jTable2.getValueAt(baris, 0).toString());
            JT_namabarang.setText(jTable2.getValueAt(baris, 1).toString());
            jt_jenisbarang.setText(jTable2.getValueAt(baris, 2).toString());
            jt_jumlahbarang.setText(jTable2.getValueAt(baris, 0).toString());

        } catch (Exception e) {
            System.err.println("Error :" + e);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT_idbarang;
    private javax.swing.JTextField JT_namabarang;
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tutup;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jt_jenisbarang;
    private javax.swing.JTextField jt_jumlahbarang;
    // End of variables declaration//GEN-END:variables
}
